name: CD Web Firebase Mainnet

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: mainnet

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            ./functions/package-lock.json
      - run: npm ci
      - run: npm run build:web
      - run: npm run test:web -- --browsers=ChromeHeadless --no-watch --no-progress
      - run: npm run e2e:web:ci
      - run: npm run build:admin
      - run: npm run test:admin -- --browsers=ChromeHeadless --no-watch --no-progress
      - run: npm run e2e:admin:ci
      - run: npm run build:lp
      - run: npm run test:lp -- --browsers=ChromeHeadless --no-watch --no-progress
      - run: npm run e2e:lp:ci
      - run: npm ci --prefix ./functions
      - run: npm run --prefix ./functions test
      - run: npx firebase deploy --project=mainnet --token=${{ secrets.FIREBASE_TOKEN }} --force
